/** Declaration file generated by dts-gen */

export = browsermob_proxy_client_axios;

declare class browsermob_proxy_client_axios {
    constructor(...args: any[]);

    callRest(...args: any[]): Promise<any>;

    closeProxies(...args: any[]): Promisee<void[]>;

    createHar(...args: any[]): Promisee<void>;

    end(...args: any[]): Promise<void>;

    getHar(...args: any[]): Promise<any>;

    listProxies(...args: any[]): Promise<any>;

    setLimits(...args: any[]): Promise<any>;

    start(...args: any[]): Promise<any>;

    static createClient(...args: any[]): any;

}

