/** Declaration file generated by dts-gen */

export = browsermob_proxy_client_axios;

declare class browsermob_proxy_client_axios {
    constructor(...args: any[]);

    callRest(...args: any[]): void;

    closeProxies(...args: any[]): void;

    createHar(...args: any[]): void;

    end(...args: any[]): void;

    getHar(...args: any[]): void;

    listProxies(...args: any[]): void;

    setLimits(...args: any[]): void;

    start(...args: any[]): void;

    static createClient(...args: any[]): void;

}

